# Generated by Django 2.2.7 on 2019-12-02 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Event_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Information_classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Information_Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Time_Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Sub_Information_classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Sub_Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='qa_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='日期')),
                ('responsible_person', models.CharField(max_length=100, verbose_name='责任人')),
                ('problem_description', models.TextField(unique_for_date='data', verbose_name='问题描述')),
                ('corrective_action', models.TextField(verbose_name='整改措施')),
                ('treatment_suggestion', models.TextField(verbose_name='处理意见')),
                ('scrutator', models.CharField(max_length=100, verbose_name='检查者')),
                ('Appendix', models.FileField(blank=True, upload_to='upload/%Y/%m/%d', verbose_name='相关附件')),
                ('grade', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True, verbose_name='评分')),
                ('grade_human', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True, verbose_name='人工偏离分')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.Department', verbose_name='受检部门/大队')),
                ('event_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.Event_class', verbose_name='发生阶段')),
                ('information_Source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.Information_Source', verbose_name='信息来源')),
                ('information_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.Information_classification', verbose_name='问题分类')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.Location', verbose_name='地点')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.State', verbose_name='关闭情况')),
                ('sub_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.Sub_Department', verbose_name='受检分部/中队')),
                ('sub_information_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.Sub_Information_classification', verbose_name='问题二级分类')),
                ('team', models.ForeignKey(default='无', on_delete=django.db.models.deletion.CASCADE, to='main_web.Team', verbose_name='责任班组')),
                ('time_bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.Time_Bucket', verbose_name='时间')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='hr_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_employee_number', models.CharField(max_length=100, verbose_name='员工编号')),
                ('hr_employee_name', models.CharField(max_length=100, verbose_name='员工姓名')),
                ('hr_staff_manager', models.CharField(blank=True, max_length=10, null=True, verbose_name='是否干部')),
                ('hr_party', models.CharField(blank=True, max_length=10, null=True, verbose_name='是否党员')),
                ('hr_on_duty', models.CharField(blank=True, max_length=10, null=True, verbose_name='是否在职检查者')),
                ('hr_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_web.Department', verbose_name='部门/大队')),
                ('hr_sub_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_web.Sub_Department', verbose_name='分部/中队')),
                ('hr_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_web.Team', verbose_name='责任班组')),
            ],
        ),
    ]
