# Generated by Django 2.2.7 on 2020-05-06 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_information_classification',
            name='information_classification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_web.Information_classification', verbose_name='问题分类'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_information_classification',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True, verbose_name='分值'),
        ),
    ]
