# Generated by Django 2.2.7 on 2020-05-19 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0002_auto_20200506_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qa_info',
            name='grade_human',
        ),
    ]
